create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company text,
  rating integer not null check (rating between 1 and 5),
  message text not null,
  is_approved boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.testimonials enable row level security;

drop policy if exists "Public can submit testimonials" on public.testimonials;
create policy "Public can submit testimonials"
on public.testimonials
for insert
to anon, authenticated
with check (is_approved = (rating = 5));

drop policy if exists "Public can read approved five star testimonials" on public.testimonials;
create policy "Public can read approved five star testimonials"
on public.testimonials
for select
to anon, authenticated
using (is_approved = true and rating = 5);
